### ISSUE TITLE
Implementation for global templates (Header, Footers, Boxes)

### ISSUE THREAD

**Issue by dominictree** [whitedataDE/whitephp#5]
The current smarty implementation should offer a simple way to include global templates (like header, footer, etc.). Currently the files can be loaded only from the modules directory via whitephp implementation.

**Comment by mariusfroehlich** [comment]
Implemented into Template Class' load function as second param.

```
<?php      
$TemplateEngine = new whitephp\view\Template();
$tpl = $TemplateEngine->load("header.tpl", 1);
```

Will load template directly from the views directory, not a module directory.
